language: node_js
node_js:
- '10'
script:
- yarn build
notifications:
  email: false
  slack:
    secure: nBqwBSMSkjBZ3OoNZkAk4nHu8i/nO1kMb+fku7NRMgjwITGKHprPdvri1qK44pphUUEyP6WnFN5DiTzQrF6qyS9MY9k9n3x0woE53wAH6lz8EJyZmAX5Fvren/aKXbDLnsTTcULfwMaAsTwi4rTdc/OuNhGk5ra5vN3Ouyj7OitjjSG/S4q8q+/+vC8djAXA74w28B0pjX00IPkoC9r3f+vxbh94Bpo2wZ8WQKrfph6gviKvgpXc9IMSDnrt+zHJy45g6GrvFfrrkldtu6J6jQRuVNbT4WT1QG5sI/3p2YSMxyeYKYUfp6ms4yOoWM6m/XZIY9/Uy49trloewJByub7ONImU5e/awopvqx7xwupv+498pKMcJIzHkiM1YX8ipJoNoEtYEMSYcZvBD3XFFqIDPX9k6ijt8SJtQLhoiaTZofuiv7dsDW5NtDu1IIA2DF9dxMNXODPyxTstxseIKiXqSgmCLvfR8p7P/TGCYJmV6Yk8bjZmrs1SFMe/Wtt1GSu6cmmU4mQkU0rSCAfvL7un7/aGbcceSJp1dGmvunO4qzUTlFVEs8d7MNPJFqcCAPwnE6Mhgw6sSULfdaEJXtDYtDED0lYI5nz/oElGaM2vqQUs8s8SPcnkqfLARcqeZCj/inhqnBZac733DvF4S9gfYP69UFF3wsyQxDx/a2I=
deploy:
  provider: npm
  email: cobygiven@gmail.com
  api_key:
    secure: bV74OBNI+CPOFDHvYaylzs2Y9QC3MVjZ30Z7npBEd5x33Sy/i3c+8fNmP6lQoSZaLVJVzxszO59muntMSeIpFDrqXYgH17bVW48pVkAWuTpzF3oK8QbGt5sBcmwD3UdgRPuPYUt2hvJC1Fjdoga5rOXHlqJf7AQrOaU6sLxd7ssY1HH2TTNmZqv0ENy1/zkkUBk1POrsqEk/yPxx0Uv5BoDvFRqyyzK2ze/m2hMuk20IAOnXcelw52qySXYAamLhcGyj74GjHNTg549orm7s99Jd5ELljIm2P3M9kmvAtOlDyaPNsIt99poepjQ3ZFAXkXa2wp+be8eJ8y1cYN1MumYyXiPAdF1OvY2wj3dPyduZzkZRPxkHTrh/1WiRgo64W0Pic/2idg+9mnRRePhwoZtLgdPvfEWQ2Qp3SWT0mxjXtk3clVmn6iQT/zfG+Um8jd5c1WSqe+Wr+HtmFW1oyVSDBZrCqj/N77v0b+2SIQOzCMUXMABJhZ+wyQUtTl1BCiuNH7jPi7tIh8H170mqEp2lEdOJEw1aQGc8m5hQMBcRpaXNsFMTeJ8EBm4FGUoH4zWAJLXDF8u+g44aR6Eh/BeKNrKvO40uCzp4jj/6ssxGF4xT34jlRy/1KKYZ8njg4nCXptB+0ICJIpwecyLcTfyYtn6OBSUKTWvmS2t5lM4=
  on:
    tags: true
    repo: WessCoby/csv-json-convertor
